import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{LayoutDashboard,Boxes,PackageOpen,Truck,ShieldCheck,TriangleAlert,FileText,BarChart3,Users,Settings,Search,Bell,Menu,Warehouse}from'lucide-react';import{BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,PieChart,Pie,Cell}from'recharts';import'./style.css';
const products=[
['199071','Tarima Genérica','142 × 112 × 12.7 cm','No'],['200463','Tarima Nacional','142 × 112 × 9.5 cm','No'],['200535','Tarima Exportación','142 × 112 × 9.5 cm','Sí'],['196208','Tarima Tacón Alto','142 × 112 × 14.6 cm','No'],['199709','Tarima del Valle','125 × 102 × 13 cm','Sí'],['207195','Tarima Nestlé','90.6 × 92.5 × 10.54 cm','Sí']];
const inv=[{n:'Exportación HT',v:1250},{n:'Nacional',v:720},{n:'CAMPAR PB HT',v:510},{n:'Cajera HT',v:430}];const pie=[{name:'Entregado',value:58},{name:'Pendiente',value:27},{name:'En tránsito',value:15}];
const nav=[['Dashboard',LayoutDashboard],['Productos',Boxes],['Inventario',PackageOpen],['Entradas',Warehouse],['Entregas',Truck],['Calidad',ShieldCheck],['Incidencias',TriangleAlert],['Documentación',FileText],['Reportes',BarChart3],['Usuarios',Users],['Configuración',Settings]];
function App(){const[page,setPage]=useState('Dashboard');return <div className="app"><aside><div className="brand"><div className="mark">C</div><div><b>CAMPAR</b><small>Embalajes de madera</small></div></div><nav>{nav.map(([n,I])=><button className={page===n?'active':''} onClick={()=>setPage(n)}><I size={19}/>{n}</button>)}</nav><div className="user"><div className="avatar">IT</div><div><b>Ian Tellez</b><small>Administrador</small></div></div></aside><main><header><div><h2>{page}</h2><p>Control operativo CAMPAR · versión de prueba</p></div><div className="tools"><Search/><Bell/><div className="avatar">IT</div></div></header>{page==='Dashboard'?<Dashboard/>:page==='Productos'?<Products/>:<Placeholder page={page}/>}</main></div>}
function Dashboard(){return <section><div className="welcome"><div><h1>Bienvenido, Ian</h1><p>Resumen operativo de CAMPAR</p></div><span>Datos de demostración</span></div><div className="kpis"><Card t="Stock total" v="3,840" s="unidades"/><Card t="Entregas" v="18" s="este mes"/><Card t="Inspecciones" v="42" s="realizadas"/><Card t="Incidencias" v="4" s="abiertas" warn/></div><div className="grid"><div className="panel wide"><h3>Inventario actual</h3><ResponsiveContainer width="100%" height={250}><BarChart data={inv}><XAxis dataKey="n"/><YAxis/><Tooltip/><Bar dataKey="v" fill="#44633b" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></div><div className="panel"><h3>Estado de entregas</h3><ResponsiveContainer width="100%" height={210}><PieChart><Pie data={pie} dataKey="value" innerRadius={50} outerRadius={78}>{pie.map((_,i)=><Cell fill={['#44633b','#d6a34a','#9aa08e'][i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="legend">58% Entregado · 27% Pendiente · 15% En tránsito</div></div></div><div className="grid"><div className="panel wide"><h3>Actividad reciente</h3><div className="activity"><p>✓ Inspección completada <b>· Gustavo</b><span>14:32</span></p><p>↗ Entrada de 150 tarimas <b>· Alessandri</b><span>12:18</span></p><p>⚠ Incidencia registrada <b>· Gustavo</b><span>10:41</span></p><p>🚚 Entrega a Planta 03 <b>· Esmeralda</b><span>Ayer</span></p></div></div><div className="panel"><h3>Stock por aserradero</h3><div className="supplier"><b>Aserradero 01</b><strong>2,210</strong></div><div className="supplier"><b>Aserradero 02</b><strong>1,630</strong></div></div></div></section>}
function Card({t,v,s,warn}){return <div className={'card '+(warn?'warn':'')}><small>{t}</small><strong>{v}</strong><span>{s}</span></div>}
function Products(){return <section><div className="welcome"><div><h1>Catálogo de productos</h1><p>Modelos iniciales proporcionados para CAMPAR</p></div><button className="primary">+ Nuevo producto</button></div><div className="panel"><div className="searchbox"><Search size={18}/>Buscar por código o producto…</div><table><thead><tr><th>Código</th><th>Producto</th><th>Medidas</th><th>HT</th><th>Estado</th></tr></thead><tbody>{products.map(p=><tr>{p.map((x,i)=><td>{i===3?<span className={x==='Sí'?'tag':'tag gray'}>{x}</span>:x}</td>)}<td><span className="tag">Activo</span></td></tr>)}</tbody></table></div></section>}
function Placeholder({page}){return <section><div className="empty"><Menu size={44}/><h1>{page}</h1><p>Módulo preparado para la siguiente iteración de CAMPAR v0.1.</p><span>La navegación ya funciona; aquí agregaremos los formularios y datos correspondientes.</span></div></section>};createRoot(document.getElementById('root')).render(<App/>);
